- name: Deploy to server
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.HOST }}
    username: ubuntu
    key: ${{ secrets.SSH_KEY }}
    script: |
      REPO_DIR=/home/ubuntu/YoloService
      REPO_URL=https://github.com/TameerAmer/YoloService.git

      sudo apt update
      sudo apt install -y python3 python3-venv python3-pip

      if [ ! -d "$REPO_DIR" ]; then
        git clone $REPO_URL $REPO_DIR
      fi

      cd $REPO_DIR
      git pull origin main

      if [ ! -d ".venv" ]; then
        python3 -m venv .venv
      fi

      source .venv/bin/activate
      pip install -r requirements.txt
      pip install -r torch-requirements.txt

      # Create systemd service file if it does not exist or overwrite
      sudo tee /etc/systemd/system/yolo.service > /dev/null <<EOF
[Unit]
Description=Yolo Service
After=network.target

[Service]
WorkingDirectory=$REPO_DIR
ExecStart=$REPO_DIR/.venv/bin/python $REPO_DIR/app.py
Restart=always
User=ubuntu

[Install]
WantedBy=multi-user.target
EOF

      # Reload systemd daemon and enable/start service
      sudo systemctl daemon-reload
      sudo systemctl enable yolo
      sudo systemctl restart yolo
      sudo systemctl status yolo
